### ISSUE TITLE
"fallback.call is not a function"

### ISSUE THREAD

**Issue by Porges** [dazuaz/responsive-loader#112]
After updating to 2.0.0 from 1.2.0 I get this error on load. Has something changed about how the loader function is exported?

The config I am using looks much like the one in the examples; I am using it as a fallback for `url-loader` so `{ fallback: "responsive-loader", etc... }`.

**Comment by dazuaz** [comment]
@Porges Hey, I have pushed a new patch that should fix this issue, if you npm update, it should work now.

Thanks for reporting this,
